### GET request to example server
GET http://localhost:8080/api/text
Content-Type: text/plain

### GET request to example server
GET http://localhost:8080/api/json
Content-Type: application/json

### GET request to example server
GET http://localhost:8080/api/notJson
Content-Type: application/json

### GET request to example server
GET http://localhost:8080/api/notJson
Content-Type: text/plain

### GET request to example server
GET http://localhost:8080/api/myHeader
My-Header: myValue