### Send POST request with json body
POST http://localhost:8080/restTest
Content-Type: application/json

{
  "name": "springmvc",
  "age": 10
}

### Send POST request with json body
POST http://localhost:8080/restTest
Content-Type: text/plain

name=springmvc,
age=10

###