### GET request to example server
GET http://localhost:8081/api/order

### GET request to example server
POST http://localhost:8081/api/order

### GET request to example server
GET http://localhost:8081/api/user

### POST request to example server
POST http://localhost:8081/api/user