### GET request to example server
GET http://localhost:8081/greet?username=springmvc

### POST request to example server
POST http://localhost:8081/greet
Content-Type: application/x-www-form-urlencoded

username = springmvc

### GET request to example server
GET http://localhost:8081/requiredTrue?username=springmvc
#GET http://localhost:8081/requiredTrue?username=
#GET http://localhost:8081/requiredTrue

### GET request to example server
GET http://localhost:8081/requiredFalse?username=springmvc
#GET http://localhost:8081/requiredFalse

### GET request to example server
GET http://localhost:8081/defaultValue?username=springmvc
#GET http://localhost:8081/defaultValue