### Send POST request with body as parameters
POST http://localhost:8081/url
Content-Type: application/x-www-form-urlencoded

url=http://www.springmvc.com:8081
#protocol=http&domain=www.springmvc.com&port=8081&ipAddress=127.0.0.1

### Send POST request with body as parameters
POST http://localhost:8081/users
Content-Type: application/x-www-form-urlencoded

user=springmvc

### Send POST request with body as parameters
GET http://localhost:8081/color?color=red