### Send POST request with body as parameters
POST http://localhost:8081/submitDate
Content-Type: application/x-www-form-urlencoded

date=2025-03-10
#date=2025/03/10

### Send POST request with body as parameters
POST http://localhost:8081/users
Content-Type: application/x-www-form-urlencoded

username = springmvc &
email = a@a.com &
password =1234