### Send POST request with body as parameters
POST http://localhost:8081/validation
Content-Type: application/x-www-form-urlencoded

username=springmvc&age=10

### Send POST request with body as parameters
POST http://localhost:8081/nonValidation
Content-Type: application/x-www-form-urlencoded

username=springmvc&age=ddd

### Send POST request with body as parameters
POST http://localhost:8081/validation2
Content-Type: application/x-www-form-urlencoded

username=springmvc&age=ddd