### Send GET request
GET http://localhost:8081/api/users

### Send GET request
GET http://localhost:8081/api/public/users

### Send GET request
GET http://localhost:8081/login

### Send GET request
GET http://localhost:8081/log

### Send GET request
GET http://localhost:8081/admin
Role: ADMIN

### Send GET request
GET http://localhost:8081/order

### Send GET request
GET http://localhost:8081/jsonError
Accept: application/json