### GET request to example server
GET http://localhost:8080/profile

### GET request to example server
GET http://localhost:8080/profile/user

### GET request to example server
GET http://localhost:8080/profile/user/1

### GET request to example server
GET http://localhost:8080/profile/mypage

### GET request to example server
GET http://localhost:8080/profile/view

### GET request to example server
GET http://localhost:8080/profile/edit