### GET request to example server
GET http://localhost:8081/profile

### GET request to example server
GET http://localhost:8081/profile/user

### GET request to example server
GET http://localhost:8081/profile/user/1

### GET request to example server
GET http://localhost:8081/profile/mypage

### GET request to example server
GET http://localhost:8081/profile/view

### GET request to example server
GET http://localhost:8081/profile/edit